# Earthquake and FAANG Data Analysis

### This notebook analyzes earthquake and stock market datasets using pandas and NumPy.

# PART-1

Load the dataset data/parsed.csv into a pandas DataFrame and complete the
following tasks using only pandas and NumPy where necessary.

In [1]:
#Import libraries
import pandas as pd
import numpy as np

In [2]:
#Load the dataset
df = pd.read_csv("/home/marie/code/Python-AI_assignment/assign3_data/parsed.csv")

In [3]:
df.tail()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
9327,NaN,NaN,73086771,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01806,NaN,185.0,",nc73086771,",0.62,md,...,reviewed,1537230228060,"M 0.6 - 9km ENE of Mammoth Lakes, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1537285598315,https://earthquake.usgs.gov/earthquakes/eventp...,California
9328,NaN,NaN,38063967,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.03041,NaN,50.0,",ci38063967,",1.00,ml,...,reviewed,1537230135130,"M 1.0 - 3km W of Julian, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1537276800970,https://earthquake.usgs.gov/earthquakes/eventp...,California
9329,NaN,NaN,2018261000,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.45260,NaN,276.0,",pr2018261000,",2.40,md,...,reviewed,1537229908180,"M 2.4 - 35km NNE of Hatillo, Puerto Rico",0,earthquake,",geoserve,origin,phase-data,",-240.0,1537243777410,https://earthquake.usgs.gov/earthquakes/eventp...,Puerto Rico
9330,NaN,NaN,38063959,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01865,NaN,61.0,",ci38063959,",1.10,ml,...,reviewed,1537229545350,"M 1.1 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537230211640,https://earthquake.usgs.gov/earthquakes/eventp...,California
9331,NaN,NaN,38063935,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.01698,NaN,39.0,",ci38063935,",0.66,ml,...,reviewed,1537228864470,"M 0.7 - 9km NE of Aguanga, CA",0,earthquake,",focal-mechanism,geoserve,nearby-cities,origin...",-480.0,1537305830770,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [4]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url', 'parsed_place'],
      dtype='object')

#### 1. Percentile Calculation: 
Find the 95th percentile of earthquake magnitude in Japan where the magType is 'mb'.

In [5]:
japan_mb = df[(df['parsed_place'].str.contains("Japan", case= False, na=False)) & (df['magType'] == 'mb')]

percentile_95 = np.percentile(japan_mb['mag'], 95)

In [6]:
percentile_95

np.float64(4.9)

#### 2. Tsunami Percentage (Indonesia): 
Calculate the percentage of earthquakes in Indonesia that were associated with a tsunami.

In [7]:
indonesia_eq = df[df['parsed_place'].str.contains("Indonesia", case= False, na= False)]

tsunami_count = indonesia_eq['tsunami'].sum()
total_eq = len(indonesia_eq)

tsunami_percentage = (tsunami_count/total_eq) * 100

In [8]:
tsunami_percentage

np.float64(23.12925170068027)

#### 3. Summary Statistics (Nevada): 
Generate summary statistics (count, mean, std, min, quartiles, max) for earthquakes that occurred in Nevada.

In [9]:
nevada_eq = df[df['parsed_place'].str.contains("Nevada", case = False, na = False)]

summary_stats = nevada_eq['mag'].describe()

In [10]:
summary_stats

count    681.000000
mean       0.500073
std        0.696710
min       -0.500000
25%       -0.100000
50%        0.400000
75%        0.900000
max        2.900000
Name: mag, dtype: float64

#### 4. Ring of Fire Classification:
Add a new column to the DataFrame called ring_of_fire that indicates whether the earthquake occurred in a country or U.S. state located on the
Ring of Fire.

Use the following locations:

Bolivia, Chile, Ecuador, Peru, Costa Rica, Guatemala, Mexico, *(Be careful not to include New Mexico)* Japan, Philippines, Indonesia, New Zealand, Antarctic
Canada, Fiji, Alaska, Washington, California
Russia, Taiwan, Tonga, Kermadec Islands

The column should contain:

● True if the earthquake occurred in one of these locations

● False otherwise

In [11]:
ring_locations = {"Bolivia", "Chile", "Ecuador", "Peru", "Costa Rica", "Guatemala", "Mexico", "Japan", "Philippines", "Indonesia", "New Zealand", "Antarctic", "Canada", "Fiji", "Alaska", "Washington", "California", "Russia", "Taiwan", "Tonga", "Kermadec Islands"}

In [12]:
def check_ring_of_fire(parsed_place):
    if pd.isna(parsed_place):
        return False
    
    for loc in ring_locations:
        if loc in parsed_place:
            if "New Mexico" in parsed_place:
                return False
            return True
    
    return False

In [13]:
df['ring_of_fire'] = df['parsed_place'].apply(check_ring_of_fire)

df[['parsed_place', 'ring_of_fire']].tail()

     parsed_place  ring_of_fire
9327   California          True
9328   California          True
9329  Puerto Rico         False
9330   California          True
9331   California          True

#### 5. Earthquake Counts (Inside vs Outside Ring of Fire)
Calculate:

● The number of earthquakes that occurred within the Ring of Fire

● The number of earthquakes that occurred outside the Ring of Fire

In [14]:
ring_counts = df['ring_of_fire'].value_counts()

inside_ring = ring_counts.get(True, 0)
outside_ring = ring_counts.get(False, 0)

In [15]:
print("Earthquake occured within the Ring of fire:", inside_ring)
print("Earthquake occured outside the Ring of fire:", outside_ring)

Earthquake occured within the Ring of fire: 7188
Earthquake occured outside the Ring of fire: 2144

#### 6. Tsunami Count Along the Ring of Fire
Find the total number of earthquakes in Ring of Fire locations that were associated with a
tsunami.

In [16]:
ring_tsunami = df[(df['ring_of_fire'] == True) & (df['tsunami']==1)]

tsunami_ring_counts = len(ring_tsunami)

In [17]:
tsunami_ring_counts

45

# PART-II
Using the CSV files in the data/ folder and what we have learned so far, complete the
following exercises:

In [18]:
#import libraries (as here's already imported in above part)

# import pandas as pd
# import numpy as np

In [19]:
#Load dataset from the data folder

earthquakes = pd.read_csv('assign3_data/earthquakes.csv')
faang = pd.read_csv('assign3_data/faang.csv')
parsed = pd.read_csv('assign3_data/parsed.csv')

In [20]:
# earthquakes.head(3)
faang.head(3)
# parsed.tail(3)

,ticker,date,high,low,open,close,volume
0,FB,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900.0
1,FB,2018-01-03,184.779999,181.330002,181.880005,184.669998,16886600.0
2,FB,2018-01-04,186.210007,184.100006,184.899994,184.330002,13880900.0

#### 1. Filtering (earthquakes.csv):
Select all earthquakes that occurred in Japan with magType equal to 'mb' and magnitude ≥ 4.9.

In [21]:
japan_quakes = earthquakes[(earthquakes['parsed_place'].str.contains("Japan", case = False, na = False)) & (earthquakes['magType']== 'mb') & (earthquakes['mag'] >= 4.9)]

japan_quakes

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

#### 2. Binning + Counts (earthquakes.csv): 
For earthquakes with magType equal to 'ml', create magnitude bins for each whole number (0–1, 1–2, 2–3, ...) and count how many earthquakes fall into each bin.

In [22]:
ml_quakes = earthquakes[earthquakes['magType'] == 'ml'].copy()

bins = np.arange(0, ml_quakes['mag'].max() +1, 1)

ml_quakes['mag_bin'] = pd.cut(ml_quakes['mag'], bins)

bin_counts = ml_quakes['mag_bin'].value_counts().sort_index()

bin_counts

mag_bin
(0.0, 1.0]    2207
(1.0, 2.0]    3105
(2.0, 3.0]     862
(3.0, 4.0]     122
(4.0, 5.0]       2
(5.0, 6.0]       1
Name: count, dtype: int64

#### 3. Groupby + Resample + Aggregation (faang.csv): 
Group by ticker, resample to monthly frequency, and compute:

1. mean of open

2. max of high

3. min of low

4. mean of close

5. sum of volume

In [23]:
faang['date'] = pd.to_datetime(faang['date'])

faang = faang.set_index('date').copy()

monthly_stats = (faang.groupby('ticker').resample('ME').agg({
    'open': 'mean',
    'high': 'max',
    'low': 'min',
    'close': 'mean',
    'volume': 'sum'
}))

In [24]:
monthly_stats

                          open         high          low        close  \
ticker date
AAPL   2018-01-31    43.505357    45.025002    41.174999    43.501309
       2018-02-28    41.819079    45.154999    37.560001    41.909737
       2018-03-31    43.761786    45.875000    41.235001    43.624048
       2018-04-30    42.441310    44.735001    40.157501    42.458572
       2018-05-31    46.239091    47.592499    41.317501    46.384205
       2018-06-30    47.180119    48.549999    45.182499    47.155357
       2018-07-31    47.549048    48.990002    45.855000    47.577857
       2018-08-31    53.121739    57.217499    49.327499    53.336522
       2018-09-30    55.582763    57.417500    53.825001    55.518421
       2018-10-31    55.300000    58.367500    51.522499    55.211413
       2018-11-30    47.954881    55.590000    42.564999    47.808929
       2018-12-31    41.310789    46.235001    36.647499    41.066579
AMZN   2018-01-31  1301.377151  1472.579956  1170.510010  1309.010946
       2018-02-28  1447.113159  1528.699951  1265.930054  1442.363146
       2018-03-31  1542.160464  1617.540039  1365.199951  1540.367629
       2018-04-30  1475.841902  1638.099976  1352.880005  1468.220471
       2018-05-31  1590.474543  1635.000000  1546.020020  1594.903637
       2018-06-30  1699.088582  1763.099976  1635.089966  1698.823812
       2018-07-31  1786.305716  1880.050049  1678.060059  1784.649042
       2018-08-31  1891.957833  2025.569946  1776.020020  1897.851308
       2018-09-30  1969.239476  2050.500000  1865.000000  1966.077900
       2018-10-31  1799.630865  2033.189941  1476.359985  1782.058265
       2018-11-30  1622.323806  1784.000000  1420.000000  1625.483823
       2018-12-31  1572.922100  1778.339966  1307.000000  1559.443154
FB     2018-01-31   184.584284   190.660004   175.800003   184.962856
       2018-02-28   180.721578   195.320007   167.179993   180.269473
       2018-03-31   173.449524   186.100006   149.020004   173.489522
       2018-04-30   164.163332   177.100006   150.509995   163.810476
       2018-05-31   181.910909   192.720001   170.229996   182.930000
       2018-06-30   194.974763   203.550003   186.429993   195.267620
       2018-07-31   199.332381   218.619995   166.559998   199.967142
       2018-08-31   177.598695   188.300003   170.270004   177.492172
       2018-09-30   164.233158   173.889999   158.869995   164.377368
       2018-10-31   154.873479   165.880005   139.029999   154.187826
       2018-11-30   141.762857   154.130005   126.849998   141.635715
       2018-12-31   137.529475   147.190002   123.019997   137.161052
GOOG   2018-01-31  1127.200945  1186.890015  1045.229980  1130.770467
       2018-02-28  1088.629472  1174.000000   992.559998  1088.206839
       2018-03-31  1096.108085  1177.050049   980.640015  1091.490479
       2018-04-30  1038.415237  1094.165039   990.369995  1035.696187
       2018-05-31  1064.021376  1110.750000  1006.289978  1069.275901
       2018-06-30  1136.396182  1186.286011  1096.010010  1137.626668
       2018-07-31  1183.464280  1273.890015  1093.800049  1187.590472
       2018-08-31  1226.156951  1256.500000  1188.239990  1225.671732
       2018-09-30  1176.878424  1212.989990  1146.910034  1175.808934
       2018-10-31  1116.082172  1209.959961   995.830017  1110.940411
       2018-11-30  1054.971424  1095.569946   996.020020  1056.162394
       2018-12-31  1042.619998  1124.650024   970.109985  1037.420519
NFLX   2018-01-31   231.269525   286.809998   195.419998   232.908096
       2018-02-28   270.873158   297.359985   236.110001   271.443683
       2018-03-31   312.712859   333.980011   275.899994   312.228097
       2018-04-30   309.129524   338.820007   271.220001   307.466192
       2018-05-31   329.779541   356.100006   305.730011   331.536819
       2018-06-30   384.557143   423.209991   352.820007   384.133336
       2018-07-31   380.969526   419.769989   328.000000   381.515238
       2018-08-31   345.410001   376.809998   310.929993   346.257824
       2018-09-30   363.326843   383.200012   335.829987   362.641576
       2018-10-31   340.025218   386.799988   271.209991   335.445652
       2018-11-30   290.643335   332.049988   250.000000   290.344764
       2018-12-31   266.309474   298.720001   231.229996   265.302630

                         volume
ticker date
AAPL   2018-01-31  2.638718e+09
       2018-02-28  3.711577e+09
       2018-03-31  2.854911e+09
       2018-04-30  2.664617e+09
       2018-05-31  2.483905e+09
       2018-06-30  2.110498e+09
       2018-07-31  1.574766e+09
       2018-08-31  2.801276e+09
       2018-09-30  2.715888e+09
       2018-10-31  3.158994e+09
       2018-11-30  3.845306e+09
       2018-12-31  3.595690e+09
AMZN   2018-01-31  9.637120e+07
       2018-02-28  1.377840e+08
       2018-03-31  1.304001e+08
       2018-04-30  1.299196e+08
       2018-05-31  7.161550e+07
       2018-06-30  8.594130e+07
       2018-07-31  9.752110e+07
       2018-08-31  9.657580e+07
       2018-09-30  9.444550e+07
       2018-10-31  1.832208e+08
       2018-11-30  1.392900e+08
       2018-12-31  1.548127e+08
FB     2018-01-31  4.956557e+08
       2018-02-28  5.162516e+08
       2018-03-31  9.962017e+08
       2018-04-30  7.500727e+08
       2018-05-31  4.011441e+08
       2018-06-30  3.872656e+08
       2018-07-31  6.470307e+08
       2018-08-31  5.488327e+08
       2018-09-30  5.004688e+08
       2018-10-31  6.224463e+08
       2018-11-30  5.181517e+08
       2018-12-31  5.587862e+08
GOOG   2018-01-31  2.873840e+07
       2018-02-28  4.238200e+07
       2018-03-31  4.535330e+07
       2018-04-30  4.171590e+07
       2018-05-31  3.184940e+07
       2018-06-30  3.209600e+07
       2018-07-31  3.194010e+07
       2018-08-31  2.880840e+07
       2018-09-30  2.886240e+07
       2018-10-31  4.849470e+07
       2018-11-30  3.673510e+07
       2018-12-31  4.025760e+07
NFLX   2018-01-31  2.383776e+08
       2018-02-28  1.845858e+08
       2018-03-31  2.634494e+08
       2018-04-30  2.620060e+08
       2018-05-31  1.420508e+08
       2018-06-30  2.440318e+08
       2018-07-31  3.053938e+08
       2018-08-31  2.131223e+08
       2018-09-30  1.708321e+08
       2018-10-31  3.635898e+08
       2018-11-30  2.571264e+08
       2018-12-31  2.343100e+08

#### 4. Crosstab with Aggregation (earthquakes.csv): 
Build a crosstab between tsunami (rows) and magType (columns). Instead of counts, show the maximum magnitude observed for each combination.

In [25]:
cross_table = pd.crosstab(earthquakes['tsunami'], earthquakes['magType'], values = earthquakes['mag'], aggfunc = 'max')

In [26]:
cross_table

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

#### 5. Z-scores with apply (faang.csv): 
For Netflix only (ticker == 'NFLX'), calculate the Z-score for each numeric column using apply().

In [27]:
nflx = faang[faang['ticker'] == 'NFLX']

numeric_cols = nflx.select_dtypes(include = np.number)

z_scores = numeric_cols.apply(lambda x: (x-x.mean())/x.std())

In [28]:
z_scores

                high       low      open     close    volume
date
2018-01-02 -2.515825 -2.410229 -2.500752 -2.416646 -0.088638
2018-01-03 -2.422985 -2.285796 -2.380291 -2.335287 -0.507472
2018-01-04 -2.405883 -2.234631 -2.296272 -2.323431 -0.959154
2018-01-05 -2.345415 -2.202090 -2.275014 -2.234304 -0.782205
2018-01-08 -2.294923 -2.143761 -2.218933 -2.192194 -1.038390
...              ...       ...       ...       ...       ...
2018-12-24 -1.518204 -1.627199 -1.571478 -1.745948 -0.338881
2018-12-26 -1.439819 -1.677341 -1.735063 -1.341403  0.517143
2018-12-27 -1.417627 -1.495807 -1.407286 -1.302563  0.134982
2018-12-28 -1.288954 -1.297287 -1.248762 -1.292138 -0.084071
2018-12-31 -1.122209 -1.088533 -1.203817 -1.055421  0.359553

[251 rows x 5 columns]

#### 6. Add Event Descriptions (faang.csv):
1. Create a DataFrame with columns ticker, date, and event using:

    ■ ticker: 'FB'

    ■ date: ['2018-07-25', '2018-03-19', '2018-03-20']

    ■ event: ['Disappointing user growth announced after close.', 'Cambridge Analytica story', 'FTC investigation']

2. Set the index to ['date', 'ticker']

3. Merge this event DataFrame with the FAANG data using an outer join.

In [29]:
events = pd.DataFrame({
    'ticker': ['FB', 'FB', 'FB'], 
    'date' :['2018-07-25', '2018-03-19', '2018-03-20'],
    'event': ['Disappointing user growth announced after close.', 'Cambridge Analytica story', 'FTC investigation']
})

events['date'] = pd.to_datetime(events['date'])

events= events.set_index(['date', 'ticker'])

faang_indexed = faang.reset_index().set_index(['date', 'ticker'])

merged_faang = faang_indexed.merge( events, how = 'outer', left_index= True, right_index = True)

In [30]:
merged_faang

                          high          low         open        close  \
date       ticker
2018-01-02 AAPL      43.075001    42.314999    42.540001    43.064999
           AMZN    1190.000000  1170.510010  1172.000000  1189.010010
           FB       181.580002   177.550003   177.679993   181.419998
           GOOG    1066.939941  1045.229980  1048.339966  1065.000000
           NFLX     201.649994   195.419998   196.100006   201.070007
...                        ...          ...          ...          ...
2018-12-31 AAPL      39.840000    39.119999    39.632500    39.435001
           AMZN    1520.760010  1487.000000  1510.800049  1501.969971
           FB       134.639999   129.949997   134.449997   131.089996
           GOOG    1052.699951  1023.590027  1050.959961  1035.609985
           NFLX     270.100006   260.000000   260.160004   267.660004

                        volume event
date       ticker
2018-01-02 AAPL    102223600.0   NaN
           AMZN      2694500.0   NaN
           FB       18151900.0   NaN
           GOOG      1237600.0   NaN
           NFLX     10966900.0   NaN
...                        ...   ...
2018-12-31 AAPL    140014000.0   NaN
           AMZN      6954500.0   NaN
           FB       24625300.0   NaN
           GOOG      1493300.0   NaN
           NFLX     13508900.0   NaN

[1255 rows x 6 columns]

#### 7. Transform to Index Values (faang.csv): 
Use transform() so that, for each ticker, all numeric values are expressed relative to the first date in that ticker’s data (divide each value by the ticker’s first-date value).

In [31]:
faang = pd.read_csv('assign3_data/faang.csv')

faang['date'] = pd.to_datetime(faang['date'])

faang = faang.sort_values(['ticker', 'date']).copy()

numeric_cols = ['open', 'high', 'low', 'close', 'volume']

faang[numeric_cols] = faang.groupby('ticker')[numeric_cols].transform(lambda x: x / x.iloc[0])

In [32]:
faang

     ticker       date      high       low      open     close    volume
251    AAPL 2018-01-02  1.000000  1.000000  1.000000  1.000000  1.000000
252    AAPL 2018-01-03  1.013059  1.015952  1.013928  0.999826  1.155033
253    AAPL 2018-01-04  1.006790  1.016661  1.013987  1.004470  0.877864
254    AAPL 2018-01-05  1.017818  1.022392  1.019276  1.015906  0.925814
255    AAPL 2018-01-08  1.019211  1.027591  1.024624  1.012133  0.804816
...     ...        ...       ...       ...       ...       ...       ...
999    NFLX 2018-12-24  1.242995  1.195783  1.234064  1.163177  0.870583
1000   NFLX 2018-12-26  1.262088  1.183246  1.192861  1.261600  1.313288
1001   NFLX 2018-12-27  1.267493  1.228636  1.275421  1.271050  1.115648
1002   NFLX 2018-12-28  1.298835  1.278272  1.315349  1.273586  1.002362
1003   NFLX 2018-12-31  1.339450  1.330468  1.326670  1.331178  1.231788

[1255 rows x 7 columns]